LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_MODULE := eom_tool
LOCAL_MODULE_TAGS := optional
LOCAL_SRC_FILES := eom_tool.c
LOCAL_C_INCLUDES+= $(TARGET_OUT_INTERMEDIATES)/KERNEL_OBJ/usr/include
LOCAL_ADDITIONAL_DEPENDENCIES += $(TARGET_OUT_INTERMEDIATES)/KERNEL_OBJ/usr

LOCAL_MODULE_PATH := $(TARGET_OUT_VENDOR)/bin

#Compiler flags
LOCAL_CFLAGS := -Wall -Wextra -Werror
#Dynamic libraries
LOCAL_SHARED_LIBRARIES := libc.vendor libm.vendor
LOCAL_MODULE_CLASS := EXECUTABLES
LOCAL_MODULE_TAGS := optional
include $(BUILD_EXECUTABLE)
